import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";
import { z } from "zod";

const HumanizerInput = z.object({
  text: z.string().min(10).max(50000),
  intensity: z.enum(["light", "medium"]),
  targetWordCount: z.number().int().positive(),
});

const STAGE1_MODEL = "meta/llama-4-maverick";
const STAGE2_MODEL = "mistral/mistral-large-3";

function buildStage1Prompt(text: string, intensity: "light" | "medium", wordCount: number): string {
  const intensityGuide =
    intensity === "light"
      ? "Make minimal structural changes. Vary sentence openings, break up a few long sentences, and add natural transitions. Preserve the author's original phrasing as much as possible."
      : "Restructure paragraphs meaningfully. Reorder some points, merge and split sentences, vary paragraph length. Change the flow while keeping all the ideas intact.";

  return `You are rewriting a piece of academic or professional writing to sound naturally human-authored.

INTENSITY: ${intensity.toUpperCase()}
${intensityGuide}

CRITICAL RULES:
- Target word count: ${wordCount} words (stay within ±3%)
- Preserve ALL facts, arguments, citations, and technical terms exactly
- Do NOT add or remove any ideas, evidence, or claims
- Do NOT use AI-typical phrases: "it is worth noting", "it is important to", "in conclusion", "furthermore", "moreover", "additionally", "in summary", "overall"
- Do NOT start consecutive sentences with the same word
- Vary sentence length naturally (mix short punchy sentences with longer ones)
- Use contractions where natural (it's, don't, we've, that's)
- Write the COMPLETE rewritten text and nothing else — no preamble, no commentary

TEXT TO REWRITE:
${text}`;
}

function buildStage2Prompt(text: string, originalWordCount: number): string {
  return `You are doing a final naturalness pass on a piece of writing. Your job is to make it read like it was written by a thoughtful human, not generated by AI.

WHAT TO DO:
- Inject natural imperfections: the occasional hedging phrase ("I think", "arguably", "in most cases"), a rhetorical question, an em dash for a sudden aside
- Vary sentence rhythm — some very short. Some longer and more flowing, with clauses that build on each other
- Use more specific, concrete word choices where generic words appear
- Occasionally use passive voice (humans do this naturally; AI avoids it)
- Break any remaining mechanical parallelism in lists or consecutive sentences

WHAT NOT TO DO:
- Do NOT change any facts, citations, arguments, or technical terms
- Do NOT add new content or remove existing ideas
- Do NOT use AI clichés ("it is worth noting", "furthermore", "in conclusion", "it is important to")
- Target word count: ${originalWordCount} words (stay within ±3%)

Write ONLY the final text. No commentary.

TEXT:
${text}`;
}

export const Route = createFileRoute("/api/humanizer-stream")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const SUPABASE_URL = process.env.SUPABASE_URL;
        const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;
        if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
          return new Response("Server misconfigured", { status: 500 });
        }

        const authHeader = request.headers.get("authorization");
        if (!authHeader?.startsWith("Bearer ")) {
          return new Response("Unauthorized", { status: 401 });
        }
        const token = authHeader.replace("Bearer ", "");
        const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
          global: { headers: { Authorization: `Bearer ${token}` } },
          auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
        });
        const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
        if (claimsError || !claimsData?.claims?.sub) {
          return new Response("Unauthorized", { status: 401 });
        }

        let body: unknown;
        try { body = await request.json(); } catch {
          return new Response("Invalid JSON", { status: 400 });
        }
        const parsed = HumanizerInput.safeParse(body);
        if (!parsed.success) {
          return new Response(`Invalid input: ${parsed.error.message}`, { status: 400 });
        }

        const { text, intensity, targetWordCount } = parsed.data;
        const { createAi, toTextStreamResponseWithErrors } = await import("@/lib/ai-gateway.server");
        const { streamText, generateText } = await import("ai");

        const ai = createAi();

        try {
          // Stage 1: structural rewrite with Llama 4 Maverick
          const stage1Result = await generateText({
            model: ai(STAGE1_MODEL),
            prompt: buildStage1Prompt(text, intensity, targetWordCount),
            temperature: intensity === "light" ? 0.6 : 0.85,
            maxOutputTokens: 8000,
          });

          const stage1Text = stage1Result.text.trim();

          // Stage 2: stream naturalness pass with Mistral Large
          const stage2Stream = streamText({
            model: ai(STAGE2_MODEL),
            prompt: buildStage2Prompt(stage1Text, targetWordCount),
            temperature: 0.75,
            maxOutputTokens: 8000,
            onError: ({ error }) => {
              console.error("[humanizer-stream] stage2 error:", error);
            },
          });

          return toTextStreamResponseWithErrors(stage2Stream);
        } catch (e) {
          console.error("[humanizer-stream] error:", e);
          return new Response(e instanceof Error ? e.message : "Humanizer failed", { status: 500 });
        }
      },
    },
  },
});
