/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPresentationsStreamRouteImport } from './routes/api.presentations-stream'
import { Route as ApiFormattingStreamRouteImport } from './routes/api.formatting-stream'
import { Route as ApiFormattingEnhanceStreamRouteImport } from './routes/api.formatting-enhance-stream'
import { Route as ApiApplyCorrectionsStreamRouteImport } from './routes/api.apply-corrections-stream'
import { Route as ApiAnalyzeStreamRouteImport } from './routes/api.analyze-stream'
import { Route as ApiAgentStreamRouteImport } from './routes/api.agent-stream'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app.projects'
import { Route as AuthenticatedAppPresentationsRouteImport } from './routes/_authenticated/app.presentations'
import { Route as AuthenticatedAppPersonasRouteImport } from './routes/_authenticated/app.personas'
import { Route as AuthenticatedAppInterviewsRouteImport } from './routes/_authenticated/app.interviews'
import { Route as AuthenticatedAppFormattingRouteImport } from './routes/_authenticated/app.formatting'
import { Route as AuthenticatedAppFillRouteImport } from './routes/_authenticated/app.fill'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppAnalyzeRouteImport } from './routes/_authenticated/app.analyze'
import { Route as AuthenticatedAppAgentRouteImport } from './routes/_authenticated/app.agent'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app.projects.index'
import { Route as AuthenticatedAppFoldersIndexRouteImport } from './routes/_authenticated/app.folders.index'
import { Route as AuthenticatedAppProjectsIdRouteImport } from './routes/_authenticated/app.projects.$id'
import { Route as AuthenticatedAppFoldersIdRouteImport } from './routes/_authenticated/app.folders.$id'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationsStreamRoute = ApiPresentationsStreamRouteImport.update({
  id: '/api/presentations-stream',
  path: '/api/presentations-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormattingStreamRoute = ApiFormattingStreamRouteImport.update({
  id: '/api/formatting-stream',
  path: '/api/formatting-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormattingEnhanceStreamRoute =
  ApiFormattingEnhanceStreamRouteImport.update({
    id: '/api/formatting-enhance-stream',
    path: '/api/formatting-enhance-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApplyCorrectionsStreamRoute =
  ApiApplyCorrectionsStreamRouteImport.update({
    id: '/api/apply-corrections-stream',
    path: '/api/apply-corrections-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAnalyzeStreamRoute = ApiAnalyzeStreamRouteImport.update({
  id: '/api/analyze-stream',
  path: '/api/analyze-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStreamRoute = ApiAgentStreamRouteImport.update({
  id: '/api/agent-stream',
  path: '/api/agent-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPresentationsRoute =
  AuthenticatedAppPresentationsRouteImport.update({
    id: '/presentations',
    path: '/presentations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPersonasRoute =
  AuthenticatedAppPersonasRouteImport.update({
    id: '/personas',
    path: '/personas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInterviewsRoute =
  AuthenticatedAppInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFormattingRoute =
  AuthenticatedAppFormattingRouteImport.update({
    id: '/formatting',
    path: '/formatting',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFillRoute = AuthenticatedAppFillRouteImport.update({
  id: '/fill',
  path: '/fill',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnalyzeRoute = AuthenticatedAppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgentRoute = AuthenticatedAppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppFoldersIndexRoute =
  AuthenticatedAppFoldersIndexRouteImport.update({
    id: '/folders/',
    path: '/folders/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsIdRoute =
  AuthenticatedAppProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppFoldersIdRoute =
  AuthenticatedAppFoldersIdRouteImport.update({
    id: '/folders/$id',
    path: '/folders/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/agent-stream': typeof ApiAgentStreamRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
  '/api/apply-corrections-stream': typeof ApiApplyCorrectionsStreamRoute
  '/api/formatting-enhance-stream': typeof ApiFormattingEnhanceStreamRoute
  '/api/formatting-stream': typeof ApiFormattingStreamRoute
  '/api/presentations-stream': typeof ApiPresentationsStreamRoute
  '/app/agent': typeof AuthenticatedAppAgentRoute
  '/app/analyze': typeof AuthenticatedAppAnalyzeRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/fill': typeof AuthenticatedAppFillRoute
  '/app/formatting': typeof AuthenticatedAppFormattingRoute
  '/app/interviews': typeof AuthenticatedAppInterviewsRoute
  '/app/personas': typeof AuthenticatedAppPersonasRoute
  '/app/presentations': typeof AuthenticatedAppPresentationsRoute
  '/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/folders/$id': typeof AuthenticatedAppFoldersIdRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/app/folders/': typeof AuthenticatedAppFoldersIndexRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/agent-stream': typeof ApiAgentStreamRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
  '/api/apply-corrections-stream': typeof ApiApplyCorrectionsStreamRoute
  '/api/formatting-enhance-stream': typeof ApiFormattingEnhanceStreamRoute
  '/api/formatting-stream': typeof ApiFormattingStreamRoute
  '/api/presentations-stream': typeof ApiPresentationsStreamRoute
  '/app/agent': typeof AuthenticatedAppAgentRoute
  '/app/analyze': typeof AuthenticatedAppAnalyzeRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/fill': typeof AuthenticatedAppFillRoute
  '/app/formatting': typeof AuthenticatedAppFormattingRoute
  '/app/interviews': typeof AuthenticatedAppInterviewsRoute
  '/app/personas': typeof AuthenticatedAppPersonasRoute
  '/app/presentations': typeof AuthenticatedAppPresentationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/folders/$id': typeof AuthenticatedAppFoldersIdRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/app/folders': typeof AuthenticatedAppFoldersIndexRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/agent-stream': typeof ApiAgentStreamRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
  '/api/apply-corrections-stream': typeof ApiApplyCorrectionsStreamRoute
  '/api/formatting-enhance-stream': typeof ApiFormattingEnhanceStreamRoute
  '/api/formatting-stream': typeof ApiFormattingStreamRoute
  '/api/presentations-stream': typeof ApiPresentationsStreamRoute
  '/_authenticated/app/agent': typeof AuthenticatedAppAgentRoute
  '/_authenticated/app/analyze': typeof AuthenticatedAppAnalyzeRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/fill': typeof AuthenticatedAppFillRoute
  '/_authenticated/app/formatting': typeof AuthenticatedAppFormattingRoute
  '/_authenticated/app/interviews': typeof AuthenticatedAppInterviewsRoute
  '/_authenticated/app/personas': typeof AuthenticatedAppPersonasRoute
  '/_authenticated/app/presentations': typeof AuthenticatedAppPresentationsRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/folders/$id': typeof AuthenticatedAppFoldersIdRoute
  '/_authenticated/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/_authenticated/app/folders/': typeof AuthenticatedAppFoldersIndexRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/app'
    | '/api/agent-stream'
    | '/api/analyze-stream'
    | '/api/apply-corrections-stream'
    | '/api/formatting-enhance-stream'
    | '/api/formatting-stream'
    | '/api/presentations-stream'
    | '/app/agent'
    | '/app/analyze'
    | '/app/dashboard'
    | '/app/fill'
    | '/app/formatting'
    | '/app/interviews'
    | '/app/personas'
    | '/app/presentations'
    | '/app/projects'
    | '/app/settings'
    | '/app/folders/$id'
    | '/app/projects/$id'
    | '/app/folders/'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/app'
    | '/api/agent-stream'
    | '/api/analyze-stream'
    | '/api/apply-corrections-stream'
    | '/api/formatting-enhance-stream'
    | '/api/formatting-stream'
    | '/api/presentations-stream'
    | '/app/agent'
    | '/app/analyze'
    | '/app/dashboard'
    | '/app/fill'
    | '/app/formatting'
    | '/app/interviews'
    | '/app/personas'
    | '/app/presentations'
    | '/app/settings'
    | '/app/folders/$id'
    | '/app/projects/$id'
    | '/app/folders'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/_authenticated/app'
    | '/api/agent-stream'
    | '/api/analyze-stream'
    | '/api/apply-corrections-stream'
    | '/api/formatting-enhance-stream'
    | '/api/formatting-stream'
    | '/api/presentations-stream'
    | '/_authenticated/app/agent'
    | '/_authenticated/app/analyze'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/fill'
    | '/_authenticated/app/formatting'
    | '/_authenticated/app/interviews'
    | '/_authenticated/app/personas'
    | '/_authenticated/app/presentations'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/folders/$id'
    | '/_authenticated/app/projects/$id'
    | '/_authenticated/app/folders/'
    | '/_authenticated/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ApiAgentStreamRoute: typeof ApiAgentStreamRoute
  ApiAnalyzeStreamRoute: typeof ApiAnalyzeStreamRoute
  ApiApplyCorrectionsStreamRoute: typeof ApiApplyCorrectionsStreamRoute
  ApiFormattingEnhanceStreamRoute: typeof ApiFormattingEnhanceStreamRoute
  ApiFormattingStreamRoute: typeof ApiFormattingStreamRoute
  ApiPresentationsStreamRoute: typeof ApiPresentationsStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentations-stream': {
      id: '/api/presentations-stream'
      path: '/api/presentations-stream'
      fullPath: '/api/presentations-stream'
      preLoaderRoute: typeof ApiPresentationsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/formatting-stream': {
      id: '/api/formatting-stream'
      path: '/api/formatting-stream'
      fullPath: '/api/formatting-stream'
      preLoaderRoute: typeof ApiFormattingStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/formatting-enhance-stream': {
      id: '/api/formatting-enhance-stream'
      path: '/api/formatting-enhance-stream'
      fullPath: '/api/formatting-enhance-stream'
      preLoaderRoute: typeof ApiFormattingEnhanceStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply-corrections-stream': {
      id: '/api/apply-corrections-stream'
      path: '/api/apply-corrections-stream'
      fullPath: '/api/apply-corrections-stream'
      preLoaderRoute: typeof ApiApplyCorrectionsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-stream': {
      id: '/api/analyze-stream'
      path: '/api/analyze-stream'
      fullPath: '/api/analyze-stream'
      preLoaderRoute: typeof ApiAnalyzeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-stream': {
      id: '/api/agent-stream'
      path: '/api/agent-stream'
      fullPath: '/api/agent-stream'
      preLoaderRoute: typeof ApiAgentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/presentations': {
      id: '/_authenticated/app/presentations'
      path: '/presentations'
      fullPath: '/app/presentations'
      preLoaderRoute: typeof AuthenticatedAppPresentationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/personas': {
      id: '/_authenticated/app/personas'
      path: '/personas'
      fullPath: '/app/personas'
      preLoaderRoute: typeof AuthenticatedAppPersonasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/interviews': {
      id: '/_authenticated/app/interviews'
      path: '/interviews'
      fullPath: '/app/interviews'
      preLoaderRoute: typeof AuthenticatedAppInterviewsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/formatting': {
      id: '/_authenticated/app/formatting'
      path: '/formatting'
      fullPath: '/app/formatting'
      preLoaderRoute: typeof AuthenticatedAppFormattingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/fill': {
      id: '/_authenticated/app/fill'
      path: '/fill'
      fullPath: '/app/fill'
      preLoaderRoute: typeof AuthenticatedAppFillRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analyze': {
      id: '/_authenticated/app/analyze'
      path: '/analyze'
      fullPath: '/app/analyze'
      preLoaderRoute: typeof AuthenticatedAppAnalyzeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agent': {
      id: '/_authenticated/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AuthenticatedAppAgentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/folders/': {
      id: '/_authenticated/app/folders/'
      path: '/folders'
      fullPath: '/app/folders/'
      preLoaderRoute: typeof AuthenticatedAppFoldersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects/$id': {
      id: '/_authenticated/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/folders/$id': {
      id: '/_authenticated/app/folders/$id'
      path: '/folders/$id'
      fullPath: '/app/folders/$id'
      preLoaderRoute: typeof AuthenticatedAppFoldersIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppProjectsRouteChildren {
  AuthenticatedAppProjectsIdRoute: typeof AuthenticatedAppProjectsIdRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
}

const AuthenticatedAppProjectsRouteChildren: AuthenticatedAppProjectsRouteChildren =
  {
    AuthenticatedAppProjectsIdRoute: AuthenticatedAppProjectsIdRoute,
    AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
  }

const AuthenticatedAppProjectsRouteWithChildren =
  AuthenticatedAppProjectsRoute._addFileChildren(
    AuthenticatedAppProjectsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgentRoute: typeof AuthenticatedAppAgentRoute
  AuthenticatedAppAnalyzeRoute: typeof AuthenticatedAppAnalyzeRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppFillRoute: typeof AuthenticatedAppFillRoute
  AuthenticatedAppFormattingRoute: typeof AuthenticatedAppFormattingRoute
  AuthenticatedAppInterviewsRoute: typeof AuthenticatedAppInterviewsRoute
  AuthenticatedAppPersonasRoute: typeof AuthenticatedAppPersonasRoute
  AuthenticatedAppPresentationsRoute: typeof AuthenticatedAppPresentationsRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRouteWithChildren
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppFoldersIdRoute: typeof AuthenticatedAppFoldersIdRoute
  AuthenticatedAppFoldersIndexRoute: typeof AuthenticatedAppFoldersIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgentRoute: AuthenticatedAppAgentRoute,
  AuthenticatedAppAnalyzeRoute: AuthenticatedAppAnalyzeRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppFillRoute: AuthenticatedAppFillRoute,
  AuthenticatedAppFormattingRoute: AuthenticatedAppFormattingRoute,
  AuthenticatedAppInterviewsRoute: AuthenticatedAppInterviewsRoute,
  AuthenticatedAppPersonasRoute: AuthenticatedAppPersonasRoute,
  AuthenticatedAppPresentationsRoute: AuthenticatedAppPresentationsRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRouteWithChildren,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppFoldersIdRoute: AuthenticatedAppFoldersIdRoute,
  AuthenticatedAppFoldersIndexRoute: AuthenticatedAppFoldersIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ApiAgentStreamRoute: ApiAgentStreamRoute,
  ApiAnalyzeStreamRoute: ApiAnalyzeStreamRoute,
  ApiApplyCorrectionsStreamRoute: ApiApplyCorrectionsStreamRoute,
  ApiFormattingEnhanceStreamRoute: ApiFormattingEnhanceStreamRoute,
  ApiFormattingStreamRoute: ApiFormattingStreamRoute,
  ApiPresentationsStreamRoute: ApiPresentationsStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
